# Generated by Django 5.0.6 on 2024-07-24 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Associate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TeamLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('total_amount', models.IntegerField()),
            ],
            options={
                'unique_together': {('name', 'description')},
            },
        ),
        migrations.CreateModel(
            name='PlotNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('plot_size', models.FloatField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plot_numbers', to='data.project')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('total_amount', models.IntegerField(blank=True, null=True)),
                ('discount', models.IntegerField(default=0)),
                ('deal_value', models.IntegerField(blank=True, null=True)),
                ('part_a', models.IntegerField(default=0)),
                ('part_b', models.IntegerField(default=0)),
                ('remaining_amount', models.IntegerField(blank=True, null=True)),
                ('associate_name', models.OneToOneField(blank=True, max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.associate')),
                ('plot_number', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.plotnumber')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.project')),
                ('team_leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.teamleader')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('part', models.CharField(choices=[('A', 'Cash'), ('B', 'Cheque/Loan')], max_length=1)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='data.record')),
            ],
        ),
        migrations.AddField(
            model_name='associate',
            name='team_leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associates', to='data.teamleader'),
        ),
    ]
